#!/usr/bin/env bash
# dify-stack.sh — Lifecycle management for the Dify AI platform + Qdrant
#
# Usage:
#   ./scripts/dify-stack.sh install   Pull images, seed config, install Quadlet units
#   ./scripts/dify-stack.sh start     Start the pod
#   ./scripts/dify-stack.sh stop      Stop all services
#   ./scripts/dify-stack.sh status    Show service health
#   ./scripts/dify-stack.sh logs [svc] Tail logs
#   ./scripts/dify-stack.sh restart   Restart all services
#   ./scripts/dify-stack.sh uninstall Remove Quadlet files (preserves data)
#
# First-time setup:
#   ./scripts/dify-stack.sh install
#   # Open http://localhost:3000 — create admin account on first visit
#   # Go to Settings → Model Providers → Ollama
#   # Set endpoint: http://host.containers.internal:11434

set -euo pipefail

source "$(dirname "${BASH_SOURCE[0]}")/env.sh"

POD_SERVICE="dify-stack-pod.service"
SERVICES=(
    "dify-qdrant.service"
    "dify-postgres.service"
    "dify-redis.service"
    "dify-api.service"
    "dify-worker.service"
    "dify-sandbox.service"
    "dify-ssrf-proxy.service"
    "dify-web.service"
    "dify-nginx.service"
)

DIFY_DATA="${LLM_ARC_MODELS}/dify"
DIFY_ENV="${DIFY_DATA}/dify.env"

# ── Helpers ───────────────────────────────────────────────────────

gen_secret() { openssl rand -hex 32; }

ensure_dify_env() {
    if [[ -f "$DIFY_ENV" ]]; then
        return
    fi

    log_info "Generating Dify secrets in ${DIFY_ENV}..."
    local secret_key db_pass redis_pass sandbox_key
    secret_key=$(gen_secret)
    db_pass=$(gen_secret)
    redis_pass=$(gen_secret)
    sandbox_key=$(gen_secret)

    cat > "$DIFY_ENV" <<EOF
# Generated by dify-stack.sh install — do not commit this file
SECRET_KEY=${secret_key}
DB_PASSWORD=${db_pass}
REDIS_PASSWORD=${redis_pass}
CELERY_BROKER_URL=redis://:${redis_pass}@localhost:6379/1
CELERY_RESULT_BACKEND=redis://:${redis_pass}@localhost:6379/1
CODE_EXECUTION_API_KEY=${sandbox_key}
EOF
    chmod 600 "$DIFY_ENV"
    log_ok "Secrets written to ${DIFY_ENV}"
}

# ── Commands ─────────────────────────────────────────────────────

cmd_install() {
    log_step "Installing Dify AI platform + Qdrant"

    # 1. Pull images
    log_info "Pulling container images..."
    podman pull docker.io/qdrant/qdrant:latest
    podman pull docker.io/postgres:15-alpine
    podman pull docker.io/redis:7-alpine
    podman pull docker.io/langgenius/dify-api:latest
    podman pull docker.io/langgenius/dify-web:latest
    podman pull docker.io/langgenius/dify-sandbox:latest
    podman pull docker.io/ubuntu/squid:latest
    podman pull docker.io/nginx:alpine
    log_ok "All images pulled"

    # 2. Create data directories
    log_info "Creating data directories..."
    mkdir -p \
        "${LLM_ARC_MODELS}/qdrant" \
        "${DIFY_DATA}/postgres" \
        "${DIFY_DATA}/redis" \
        "${DIFY_DATA}/storage"
    log_ok "Directories created under ${LLM_ARC_MODELS}/"

    # 3. Generate secrets
    ensure_dify_env

    # 4. Seed nginx.conf (don't overwrite user edits)
    if [[ ! -f "${DIFY_DATA}/nginx.conf" ]]; then
        cp "${LLM_ARC_CONFIG}/dify/nginx.conf" "${DIFY_DATA}/nginx.conf"
        log_ok "nginx.conf deployed"
    fi

    # 5. Seed squid.conf
    if [[ ! -f "${DIFY_DATA}/squid.conf" ]]; then
        cp "${LLM_ARC_CONFIG}/dify/squid.conf" "${DIFY_DATA}/squid.conf"
        log_ok "squid.conf deployed"
    fi

    # 6. Install Quadlet unit files
    log_info "Installing Quadlet unit files..."
    mkdir -p "$LLM_ARC_QUADLET_DIR"
    for f in "${LLM_ARC_QUADLET}"/dify-*.pod "${LLM_ARC_QUADLET}"/dify-*.container; do
        [[ -f "$f" ]] || continue
        cp "$f" "${LLM_ARC_QUADLET_DIR}/$(basename "$f")"
        log_ok "  → $(basename "$f")"
    done

    # 7. Reload systemd
    log_info "Reloading systemd..."
    systemctl --user daemon-reload
    log_ok "Installation complete"

    echo ""
    log_info "Next steps:"
    log_info "  1. Start:  ./scripts/dify-stack.sh start"
    log_info "  2. Open:   http://localhost:${LLM_ARC_DIFY_PORT}"
    log_info "  3. Create an admin account on first visit"
    log_info "  4. Settings → Model Providers → Ollama"
    log_info "     Endpoint: http://host.containers.internal:${LLM_ARC_OLLAMA_PORT}"
}

cmd_start() {
    log_step "Starting Dify stack..."
    systemctl --user start "$POD_SERVICE"
    sleep 3
    cmd_status
}

cmd_stop() {
    log_step "Stopping Dify stack..."
    systemctl --user stop "$POD_SERVICE"
    log_ok "All Dify services stopped"
}

cmd_restart() {
    log_step "Restarting Dify stack..."
    systemctl --user restart "$POD_SERVICE"
    sleep 3
    cmd_status
}

cmd_status() {
    log_step "Dify Stack Status"
    echo ""

    printf "  %-24s " "Pod:"
    if systemctl --user is-active "$POD_SERVICE" &>/dev/null; then
        printf "${GREEN}running${RESET}\n"
    else
        printf "${RED}stopped${RESET}\n"
    fi

    for svc in "${SERVICES[@]}"; do
        local name="${svc%.service}"
        printf "  %-24s " "${name}:"

        if ! systemctl --user cat "$svc" &>/dev/null 2>&1; then
            printf "${YELLOW}not installed${RESET}\n"
            continue
        fi

        local state
        state=$(systemctl --user is-active "$svc" 2>/dev/null || true)
        case "$state" in
            active)   printf "${GREEN}running${RESET}" ;;
            inactive) printf "${YELLOW}stopped${RESET}" ;;
            failed)   printf "${RED}failed${RESET}" ;;
            *)        printf "${YELLOW}${state}${RESET}" ;;
        esac

        if [[ "$state" == "active" ]]; then
            local container_name="$name"
            local health
            health=$(podman inspect --format='{{.State.Health.Status}}' "$container_name" 2>/dev/null || echo "")
            if [[ -n "$health" ]]; then
                case "$health" in
                    healthy)  printf "  ${GREEN}(healthy)${RESET}" ;;
                    starting) printf "  ${YELLOW}(starting)${RESET}" ;;
                    *)        printf "  ${RED}(${health})${RESET}" ;;
                esac
            fi
        fi
        echo ""
    done

    echo ""
    if curl -sf "http://127.0.0.1:${LLM_ARC_DIFY_PORT}" >/dev/null 2>&1; then
        log_ok "Dify UI responding at http://localhost:${LLM_ARC_DIFY_PORT}"
    fi
    if curl -sf "http://127.0.0.1:${LLM_ARC_QDRANT_PORT}/readyz" >/dev/null 2>&1; then
        log_ok "Qdrant responding at http://localhost:${LLM_ARC_QDRANT_PORT}"
    fi
}

cmd_logs() {
    local svc="${1:-}"
    if [[ -z "$svc" ]]; then
        journalctl --user -u "$POD_SERVICE" -f --no-hostname
    else
        case "$svc" in
            qdrant|postgres|redis|api|worker|web|sandbox|ssrf-proxy|nginx)
                journalctl --user -u "dify-${svc}.service" -f --no-hostname
                ;;
            *)
                log_error "Unknown service: $svc"
                log_info  "Available: qdrant, postgres, redis, api, worker, web, sandbox, ssrf-proxy, nginx"
                exit 1
                ;;
        esac
    fi
}

cmd_uninstall() {
    log_step "Uninstalling Dify stack..."
    systemctl --user stop "$POD_SERVICE" 2>/dev/null || true

    local known=(
        dify-stack.pod
        dify-qdrant.container dify-postgres.container dify-redis.container
        dify-api.container dify-worker.container dify-web.container
        dify-sandbox.container dify-ssrf-proxy.container dify-nginx.container
    )
    for name in "${known[@]}"; do
        local f="${LLM_ARC_QUADLET_DIR}/${name}"
        [[ -f "$f" ]] && rm "$f" && log_ok "Removed ${name}"
    done

    systemctl --user daemon-reload
    log_ok "Quadlet files removed"
    log_info "Data preserved at ${DIFY_DATA}/ and ${LLM_ARC_MODELS}/qdrant/"
    log_info "To remove data too: rm -rf ${DIFY_DATA} ${LLM_ARC_MODELS}/qdrant"
}

# ── Main ──────────────────────────────────────────────────────────
case "${1:-help}" in
    install)   cmd_install ;;
    start)     cmd_start ;;
    stop)      cmd_stop ;;
    restart)   cmd_restart ;;
    status)    cmd_status ;;
    logs)      cmd_logs "${2:-}" ;;
    uninstall) cmd_uninstall ;;
    help|*)
        echo "Usage: $(basename "$0") <command>"
        echo ""
        echo "Commands:"
        echo "  install    Pull images, generate secrets, install Quadlet units"
        echo "  start      Start the Dify stack pod"
        echo "  stop       Stop all Dify services"
        echo "  restart    Restart all Dify services"
        echo "  status     Show health of all Dify services"
        echo "  logs [svc] Tail logs (qdrant, postgres, redis, api, worker, web, sandbox, ssrf-proxy, nginx)"
        echo "  uninstall  Remove Quadlet files (preserves data)"
        ;;
esac
